# Generated by Django 3.1.6 on 2021-02-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0003_auto_20210213_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='pill',
            new_name='pills',
        ),
    ]
