# Generated by Django 3.1.6 on 2021-02-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0005_auto_20210213_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='pills',
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
